// <auto-generated />
using System;
using CyclingAnalyzer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyclingAnalyzer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CyclingAnalyzer.Api.Models.Entities.Athlete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("CyclingAnalyzer.Api.Models.Entities.AthleteToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId")
                        .IsUnique();

                    b.ToTable("AthleteTokens");
                });

            modelBuilder.Entity("CyclingAnalyzer.Api.Models.Entities.Ride", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("AverageHeartRate")
                        .HasColumnType("REAL");

                    b.Property<float>("AveragePowerWatts")
                        .HasColumnType("REAL");

                    b.Property<float>("AverageSpeedMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("DistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<float>("ElevationGainMeters")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxHeartRate")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxPowerWatts")
                        .HasColumnType("REAL");

                    b.Property<int>("MovingTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("WeightKgAtTime")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "StartDate");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("CyclingAnalyzer.Api.Models.Entities.AthleteToken", b =>
                {
                    b.HasOne("CyclingAnalyzer.Api.Models.Entities.Athlete", "Athlete")
                        .WithOne("Token")
                        .HasForeignKey("CyclingAnalyzer.Api.Models.Entities.AthleteToken", "AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("CyclingAnalyzer.Api.Models.Entities.Ride", b =>
                {
                    b.HasOne("CyclingAnalyzer.Api.Models.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("CyclingAnalyzer.Api.Models.Entities.Athlete", b =>
                {
                    b.Navigation("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
